### ISSUE TITLE
blokowanie subdomen w momencie gdy główna domena jest w rejestrze

### ISSUE THREAD

**Issue by lmsindeo** [epix-dev/dns-bh#4]
Zgodnie z ustawą hazardową mamy blokować konkretne domeny które sa wpisane w rejestrze.
System niestety blokuje też subdomeny w momencie gdy główna domena znajduje się w rejestrze

**Comment by awiamo** [comment]
Problemem jest to, że podczas kontroli urzędnicy sprawdzają dostępność domeny "awww.slotjerry.com". Domena ta na chwilę była wpisana w rejestr po czym została wypisana (jest obecnie w archiwum). W obecnej chwili w rejestrze znajduje się domena 
 "slotjerry.com" i kilka subdomen. Zapewne istnienie domeny "slotjerry.com" powoduje, że blokada jest zakładana na wszystkie subdomeny w domenie "*.slotjerry.com". Więc zgodnie z logiką MF należało by wykluczyć blokowanie wszystkich subdomen i nie blokować "*.domena". 
 
 W [specyfikacji i ustawie](https://www.podatki.gov.pl/pozostale-podatki/gry-hazardowe/rejestr-domen/) jest informacja o blokadzie domen. No i teraz czy zablokowanie domeny jest równoznaczne z zablokowaniem jej po całości z subdomenami - tak by wskazywała logika. Niestety urzędnik chyba miał co innego na myśli...

**Comment by akiermasz-epix** [comment]
Zmodyfikowałem działanie skryptu dns-bh.lua tak, że teraz są modyfikowane odpowiedzi na zapytania dokładnie dopasowane do zawartości pobranej z rejestru domen hazardowych.
